### ISSUE TITLE
Add a CLI flag for disabling memory leak detection

### ISSUE THREAD

**Issue by steveszc** [truecoach/ember-cli-memory-leak-detector#27]
It may be useful to conditionally disabled or enable memory leak detection when running a command like `ember test` on the command line. In particular this will be useful for setting up CI, where users may wish to only run memory leak detection as part of a certain CI command but not every time their tests are run.

Unsure if memory leak detection should be opt-in (`--detect-memory-leaks=true`) or opt-out (`--disable-memory-leak-detection=true`) 🤔

**Comment by bendemboski** [comment]
A few thoughts:

1. It might make more sense to use an environment variable rather than command-line switch. I think it would be a little easier to read from the addon, and in my experience friendlier to the scenario you describe where maybe it might be configured in CI -- then I can just set the env var rather than having to add a whole extra script to `package.json` and/or extra command-line arguments to my CI config file's invocation of `ember-cli`.
2. I'd definitely go for opt-in. This is a pretty significant change to the runtime test environment, and not something I'd really want to "accidentally" happen. I'm thinking of various test frameworks that have support for code coverage like `jest` -- none of them run coverage by default, it's something you opt in to. In this case you've arguably already opted in by installing the addon in the first place, but especially with large teams, one person opting in so they can run some specific tests probably shouldn't opt everyone in all cases in.

Also, since you can enable/disable it via the config, I would assume the cli option/env var would override that, so teams could really set it up however they want -- on by default, and the env var can turn it off, or off by default and the env var can turn it on. So maybe it's more of a setup-time config question of whether consumers set it to enabled/disabled by default in `config/environment.js`, knowing that they can toggle it either way at "runtime" using an environment variable.

**Comment by steveszc** [comment]
@bendemboski Thanks for your thoughts. Env var seems like the way to go.
